alias: null
batch_size: 64
context_size: null
dataloader_kwargs: null
decoder_hidden_size: 32
decoder_layers: 2
default_root_dir: C:\Users\77019\Desktop\code\raka\airkaz\code\lightning_logs\proc_15960
drop_last_loader: false
early_stop_patience_steps: -1
enable_checkpointing: false
encoder_bias: true
encoder_dropout: 0.0
encoder_hidden_size: 64
encoder_n_layers: 3
exclude_insample_y: false
futr_exog_list: null
h: 1
h_train: 1
hist_exog_list: null
inference_input_size: null
inference_windows_batch_size: 1024
input_size: 676
learning_rate: 0.0046537039535754325
logger: !!python/object:lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  _default_hp_metric: true
  _experiment: null
  _fs: !!python/object/apply:fsspec.spec.make_instance
  - !!python/name:fsspec.implementations.local.LocalFileSystem ''
  - !!python/tuple []
  - {}
  _kwargs: {}
  _log_graph: false
  _name: lightning_logs
  _prefix: ''
  _root_dir: C:\Users\77019\Desktop\code\raka\airkaz\code\lightning_logs
  _sub_dir: null
  _version: proc_15960
  hparams: {}
loss: &id001 !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters: {}
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 1000
n_samples: 100
n_series: 1
num_lr_decays: -1
optimizer: null
optimizer_kwargs: null
random_seed: 7
recurrent: false
scaler_type: robust
start_padding_enabled: true
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: *id001
windows_batch_size: 128
